name: gnomad_db

channels:
  - anaconda
  - conda-forge
  - bioconda

dependencies:
  - python>=3.7
  - pip
  - numpy>=1.19
  - pandas>=1.1.4
  - pyyaml
  - tqdm
  - jupyter
  - papermill>=2.3.2
  - bcftools
  
  - pip:
      - snakemake
      - pysqlite3
      - joblib
      - pytest
      - nbformat>=5.1
